from RPA.Excel.Files import Files
from classes.New import New

import logging


class NewsSpreadsheet:
    """Represents the Excel spreadsheet to be generated by the application"""

    _logger = logging.getLogger("classes.NewsSpreadsheet")

    def __init__(self):
        self._lib = Files()
        self._row = 1
        self._lib.create_workbook()
        self._lib.set_cell_values(
            "A1",
            [
                [
                    "title",
                    "date",
                    "description",
                    "picture_filename",
                    "search_phrase_count",
                    "contains_money_amount",
                ]
            ],
        )
        # possible improvement: set cell formats
        self._logger.info("news spreadsheet created")

    def add_new(self, new: New):
        self._row += 1
        self._lib.set_cell_values(
            f"A{self._row}",
            [
                [
                    new.title,
                    new.publish_date.strftime("%m/%d/%Y"),
                    new.description or "-",
                    new.pic_filename,
                    new.search_phrase_count,
                    str(new.contains_money_amount),
                ]
            ],
        )
        self._logger.info(
            f"added new with title '{new.title}' to spreadsheet; current row count is {self._row}"
        )

    def save_to(self, filename: str):
        self._lib.save_workbook(filename)
